development:
  bucket: myappdevelopment
  access_key_id: 1B7JJ1RZXMZP7VQADY02
  secret_access_key: 8UvZq1RtsyE72t0vq2U1FaaZStGXm9fj87uFub2b

test:
  bucket: myapptest
  access_key_id: 1B7JJ1RZXMZP7VQADY02
  secret_access_key: 8UvZq1RtsyE72t0vq2U1FaaZStGXm9fj87uFub2b

production:
  bucket: myapp
  access_key_id: 1B7JJ1RZXMZP7VQADY02
  secret_access_key: 8UvZq1RtsyE72t0vq2U1FaaZStGXm9fj87uFub2b